// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SukotSystemData;

#nullable disable

namespace SukotSystemData.Migrations
{
    [DbContext(typeof(DataContex))]
    [Migration("20260909112220_Migration4")]
    partial class Migration4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CityRabbi", b =>
                {
                    b.Property<int>("CoveredCitiesId")
                        .HasColumnType("integer");

                    b.Property<int>("RabbisId")
                        .HasColumnType("integer");

                    b.HasKey("CoveredCitiesId", "RabbisId");

                    b.HasIndex("RabbisId");

                    b.ToTable("RabbiCoveredCities", (string)null);
                });

            modelBuilder.Entity("SukotSystemCore.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "אלף שין",
                            PasswordHash = "100000.bv0SLUsDGpMM+srg54YgjA==.SqnUa/+8WvKmTTcyx52+m68DRrEcoasVIUVsNyAcW6o=",
                            Phone = "0556751030"
                        },
                        new
                        {
                            Id = 2,
                            FullName = "מפתחים",
                            PasswordHash = "100000.bv0SLUsDGpMM+srg54YgjA==.SqnUa/+8WvKmTTcyx52+m68DRrEcoasVIUVsNyAcW6o=",
                            Phone = "0500000000"
                        });
                });

            modelBuilder.Entity("SukotSystemCore.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "עפולה"
                        },
                        new
                        {
                            Id = 2,
                            Name = "עכו"
                        },
                        new
                        {
                            Id = 3,
                            Name = "ערד"
                        },
                        new
                        {
                            Id = 4,
                            Name = "אריאל"
                        },
                        new
                        {
                            Id = 5,
                            Name = "אשדוד"
                        },
                        new
                        {
                            Id = 6,
                            Name = "אשקלון"
                        },
                        new
                        {
                            Id = 7,
                            Name = "באקה אל-גרביה"
                        },
                        new
                        {
                            Id = 8,
                            Name = "בת ים"
                        },
                        new
                        {
                            Id = 9,
                            Name = "באר שבע"
                        },
                        new
                        {
                            Id = 10,
                            Name = "באר יעקב"
                        },
                        new
                        {
                            Id = 11,
                            Name = "בית שאן"
                        },
                        new
                        {
                            Id = 12,
                            Name = "בית שמש"
                        },
                        new
                        {
                            Id = 13,
                            Name = "ביתר עילית"
                        },
                        new
                        {
                            Id = 14,
                            Name = "בני ברק"
                        },
                        new
                        {
                            Id = 15,
                            Name = "דימונה"
                        },
                        new
                        {
                            Id = 16,
                            Name = "אילת"
                        },
                        new
                        {
                            Id = 17,
                            Name = "אלעד"
                        },
                        new
                        {
                            Id = 18,
                            Name = "גני תקווה"
                        },
                        new
                        {
                            Id = 19,
                            Name = "גבעת שמואל"
                        },
                        new
                        {
                            Id = 20,
                            Name = "גבעת זאב"
                        },
                        new
                        {
                            Id = 21,
                            Name = "גבעתיים"
                        },
                        new
                        {
                            Id = 22,
                            Name = "חדרה"
                        },
                        new
                        {
                            Id = 23,
                            Name = "חיפה"
                        },
                        new
                        {
                            Id = 24,
                            Name = "חריש"
                        },
                        new
                        {
                            Id = 25,
                            Name = "הרצליה"
                        },
                        new
                        {
                            Id = 26,
                            Name = "הוד השרון"
                        },
                        new
                        {
                            Id = 27,
                            Name = "חולון"
                        },
                        new
                        {
                            Id = 28,
                            Name = "ירושלים"
                        },
                        new
                        {
                            Id = 29,
                            Name = "כרמיאל"
                        },
                        new
                        {
                            Id = 30,
                            Name = "כפר סבא"
                        },
                        new
                        {
                            Id = 31,
                            Name = "כפר יונה"
                        },
                        new
                        {
                            Id = 32,
                            Name = "קרית אתא"
                        },
                        new
                        {
                            Id = 33,
                            Name = "קרית ביאליק"
                        },
                        new
                        {
                            Id = 34,
                            Name = "קרית גת"
                        },
                        new
                        {
                            Id = 35,
                            Name = "קרית מלאכי"
                        },
                        new
                        {
                            Id = 36,
                            Name = "קרית מוצקין"
                        },
                        new
                        {
                            Id = 37,
                            Name = "קרית אונו"
                        },
                        new
                        {
                            Id = 38,
                            Name = "קרית שמונה"
                        },
                        new
                        {
                            Id = 39,
                            Name = "קרית ים"
                        },
                        new
                        {
                            Id = 40,
                            Name = "לוד"
                        },
                        new
                        {
                            Id = 41,
                            Name = "מעלה אדומים"
                        },
                        new
                        {
                            Id = 42,
                            Name = "מעלות-תרשיחא"
                        },
                        new
                        {
                            Id = 43,
                            Name = "מגדל העמק"
                        },
                        new
                        {
                            Id = 44,
                            Name = "מודיעין-מכבים-רעות"
                        },
                        new
                        {
                            Id = 45,
                            Name = "נהריה"
                        },
                        new
                        {
                            Id = 46,
                            Name = "נצרת"
                        },
                        new
                        {
                            Id = 47,
                            Name = "נס ציונה"
                        },
                        new
                        {
                            Id = 48,
                            Name = "נשר"
                        },
                        new
                        {
                            Id = 49,
                            Name = "נתניה"
                        },
                        new
                        {
                            Id = 50,
                            Name = "נתיבות"
                        },
                        new
                        {
                            Id = 51,
                            Name = "נוף הגליל"
                        },
                        new
                        {
                            Id = 52,
                            Name = "אופקים"
                        },
                        new
                        {
                            Id = 53,
                            Name = "אור עקיבא"
                        },
                        new
                        {
                            Id = 54,
                            Name = "אור יהודה"
                        },
                        new
                        {
                            Id = 55,
                            Name = "פתח תקווה"
                        },
                        new
                        {
                            Id = 56,
                            Name = "קלנסווה"
                        },
                        new
                        {
                            Id = 57,
                            Name = "רעננה"
                        },
                        new
                        {
                            Id = 58,
                            Name = "רהט"
                        },
                        new
                        {
                            Id = 59,
                            Name = "רמת השרון"
                        },
                        new
                        {
                            Id = 60,
                            Name = "רמת גן"
                        },
                        new
                        {
                            Id = 61,
                            Name = "רמלה"
                        },
                        new
                        {
                            Id = 62,
                            Name = "רחובות"
                        },
                        new
                        {
                            Id = 63,
                            Name = "ראשון לציון"
                        },
                        new
                        {
                            Id = 64,
                            Name = "ראש העין"
                        },
                        new
                        {
                            Id = 65,
                            Name = "סחנין"
                        },
                        new
                        {
                            Id = 66,
                            Name = "שדרות"
                        },
                        new
                        {
                            Id = 67,
                            Name = "שפרעם"
                        },
                        new
                        {
                            Id = 68,
                            Name = "טייבה"
                        },
                        new
                        {
                            Id = 69,
                            Name = "תמרה"
                        },
                        new
                        {
                            Id = 70,
                            Name = "תל אביב-יפו"
                        },
                        new
                        {
                            Id = 71,
                            Name = "טבריה"
                        },
                        new
                        {
                            Id = 72,
                            Name = "טירה"
                        },
                        new
                        {
                            Id = 73,
                            Name = "טירת כרמל"
                        },
                        new
                        {
                            Id = 74,
                            Name = "צפת"
                        },
                        new
                        {
                            Id = 75,
                            Name = "אום אל-פחם"
                        },
                        new
                        {
                            Id = 76,
                            Name = "יבנה"
                        },
                        new
                        {
                            Id = 77,
                            Name = "יהוד-מונוסון"
                        },
                        new
                        {
                            Id = 78,
                            Name = "יקנעם עילית"
                        },
                        new
                        {
                            Id = 79,
                            Name = "אבו גוש"
                        },
                        new
                        {
                            Id = 80,
                            Name = "אבו סנאן"
                        },
                        new
                        {
                            Id = 81,
                            Name = "אלפי מנשה"
                        },
                        new
                        {
                            Id = 82,
                            Name = "ערערה"
                        },
                        new
                        {
                            Id = 83,
                            Name = "ערערה בנגב"
                        },
                        new
                        {
                            Id = 84,
                            Name = "עראבה"
                        },
                        new
                        {
                            Id = 85,
                            Name = "אזור"
                        },
                        new
                        {
                            Id = 86,
                            Name = "בסמ\"ה"
                        },
                        new
                        {
                            Id = 87,
                            Name = "בית אריה"
                        },
                        new
                        {
                            Id = 88,
                            Name = "בית דגן"
                        },
                        new
                        {
                            Id = 89,
                            Name = "בית אל"
                        },
                        new
                        {
                            Id = 90,
                            Name = "בית ג'ן"
                        },
                        new
                        {
                            Id = 91,
                            Name = "בנימינה-גבעת עדה"
                        },
                        new
                        {
                            Id = 92,
                            Name = "ביר אל-מכסור"
                        },
                        new
                        {
                            Id = 93,
                            Name = "בני עי\"ש"
                        },
                        new
                        {
                            Id = 94,
                            Name = "בסמת טבעון"
                        },
                        new
                        {
                            Id = 95,
                            Name = "בועיינה-נוג'ידאת"
                        },
                        new
                        {
                            Id = 96,
                            Name = "בוקעאתה"
                        },
                        new
                        {
                            Id = 97,
                            Name = "דבוריה"
                        },
                        new
                        {
                            Id = 98,
                            Name = "דיר חנא"
                        },
                        new
                        {
                            Id = 99,
                            Name = "דיר אל-אסד"
                        },
                        new
                        {
                            Id = 100,
                            Name = "אפרת"
                        },
                        new
                        {
                            Id = 101,
                            Name = "עילבון"
                        },
                        new
                        {
                            Id = 102,
                            Name = "עין קיניה"
                        },
                        new
                        {
                            Id = 103,
                            Name = "עין מאהל"
                        },
                        new
                        {
                            Id = 104,
                            Name = "אלקנה"
                        },
                        new
                        {
                            Id = 105,
                            Name = "אליכין"
                        },
                        new
                        {
                            Id = 106,
                            Name = "עמנואל"
                        },
                        new
                        {
                            Id = 107,
                            Name = "אבן יהודה"
                        },
                        new
                        {
                            Id = 108,
                            Name = "פסוטה"
                        },
                        new
                        {
                            Id = 109,
                            Name = "פורידיס"
                        },
                        new
                        {
                            Id = 110,
                            Name = "גן יבנה"
                        },
                        new
                        {
                            Id = 111,
                            Name = "גדרה"
                        },
                        new
                        {
                            Id = 112,
                            Name = "הר אדר"
                        },
                        new
                        {
                            Id = 113,
                            Name = "חצור הגלילית"
                        },
                        new
                        {
                            Id = 114,
                            Name = "חורה"
                        },
                        new
                        {
                            Id = 115,
                            Name = "חורפיש"
                        },
                        new
                        {
                            Id = 116,
                            Name = "אעבלין"
                        },
                        new
                        {
                            Id = 117,
                            Name = "אכסאל"
                        },
                        new
                        {
                            Id = 118,
                            Name = "עילוט"
                        },
                        new
                        {
                            Id = 119,
                            Name = "ג'לג'וליה"
                        },
                        new
                        {
                            Id = 120,
                            Name = "ג'סר א-זרקא"
                        },
                        new
                        {
                            Id = 121,
                            Name = "ג'דיידה-מכר"
                        },
                        new
                        {
                            Id = 122,
                            Name = "ג'וליס"
                        },
                        new
                        {
                            Id = 123,
                            Name = "כעביה-טבאש-חג'אג'רה"
                        },
                        new
                        {
                            Id = 124,
                            Name = "כאבול"
                        },
                        new
                        {
                            Id = 125,
                            Name = "קדימה-צורן"
                        },
                        new
                        {
                            Id = 126,
                            Name = "כפר ברא"
                        },
                        new
                        {
                            Id = 127,
                            Name = "כפר מנדא"
                        },
                        new
                        {
                            Id = 128,
                            Name = "כפר קרע"
                        },
                        new
                        {
                            Id = 129,
                            Name = "כפר יאסיף"
                        },
                        new
                        {
                            Id = 130,
                            Name = "קרני שומרון"
                        },
                        new
                        {
                            Id = 131,
                            Name = "קצרין"
                        },
                        new
                        {
                            Id = 132,
                            Name = "קדומים"
                        },
                        new
                        {
                            Id = 133,
                            Name = "כפר קמה"
                        },
                        new
                        {
                            Id = 134,
                            Name = "כפר כנא"
                        },
                        new
                        {
                            Id = 135,
                            Name = "כפר שמריהו"
                        },
                        new
                        {
                            Id = 136,
                            Name = "כפר תבור"
                        },
                        new
                        {
                            Id = 137,
                            Name = "כפר ורדים"
                        },
                        new
                        {
                            Id = 138,
                            Name = "קרית ארבע"
                        },
                        new
                        {
                            Id = 139,
                            Name = "קרית עקרון"
                        },
                        new
                        {
                            Id = 140,
                            Name = "קרית טבעון"
                        },
                        new
                        {
                            Id = 141,
                            Name = "קרית יערים"
                        },
                        new
                        {
                            Id = 142,
                            Name = "כסרא-סמיע"
                        },
                        new
                        {
                            Id = 143,
                            Name = "כוכב יאיר-צור יגאל"
                        },
                        new
                        {
                            Id = 144,
                            Name = "כסייפה"
                        },
                        new
                        {
                            Id = 145,
                            Name = "לקיה"
                        },
                        new
                        {
                            Id = 146,
                            Name = "להבים"
                        },
                        new
                        {
                            Id = 147,
                            Name = "מעלה עירון"
                        },
                        new
                        {
                            Id = 148,
                            Name = "מעלה אפרים"
                        },
                        new
                        {
                            Id = 149,
                            Name = "מג'אר"
                        },
                        new
                        {
                            Id = 150,
                            Name = "מג'דל שמס"
                        },
                        new
                        {
                            Id = 151,
                            Name = "מסעדה"
                        },
                        new
                        {
                            Id = 152,
                            Name = "משהד"
                        },
                        new
                        {
                            Id = 153,
                            Name = "מזכרת בתיה"
                        },
                        new
                        {
                            Id = 154,
                            Name = "מזרעה"
                        },
                        new
                        {
                            Id = 155,
                            Name = "מיתר"
                        },
                        new
                        {
                            Id = 156,
                            Name = "מטולה"
                        },
                        new
                        {
                            Id = 157,
                            Name = "מבשרת ציון"
                        },
                        new
                        {
                            Id = 158,
                            Name = "מיצד"
                        },
                        new
                        {
                            Id = 159,
                            Name = "מגדל"
                        },
                        new
                        {
                            Id = 160,
                            Name = "מגדל תפן"
                        },
                        new
                        {
                            Id = 161,
                            Name = "מצפה רמון"
                        },
                        new
                        {
                            Id = 162,
                            Name = "מודיעין עילית"
                        },
                        new
                        {
                            Id = 163,
                            Name = "נחף"
                        },
                        new
                        {
                            Id = 164,
                            Name = "נאות חובב"
                        },
                        new
                        {
                            Id = 165,
                            Name = "עומר"
                        },
                        new
                        {
                            Id = 166,
                            Name = "אורנית"
                        },
                        new
                        {
                            Id = 167,
                            Name = "פרדס חנה-כרכור"
                        },
                        new
                        {
                            Id = 168,
                            Name = "פרדסיה"
                        },
                        new
                        {
                            Id = 169,
                            Name = "פקיעין (בוקייעה)"
                        },
                        new
                        {
                            Id = 170,
                            Name = "רמת ישי"
                        },
                        new
                        {
                            Id = 171,
                            Name = "ראמה"
                        },
                        new
                        {
                            Id = 172,
                            Name = "ריינה"
                        },
                        new
                        {
                            Id = 173,
                            Name = "רכסים"
                        },
                        new
                        {
                            Id = 174,
                            Name = "ראש פינה"
                        },
                        new
                        {
                            Id = 175,
                            Name = "סאג'ור"
                        },
                        new
                        {
                            Id = 176,
                            Name = "סביון"
                        },
                        new
                        {
                            Id = 177,
                            Name = "שגב שלום"
                        },
                        new
                        {
                            Id = 178,
                            Name = "שעב"
                        },
                        new
                        {
                            Id = 179,
                            Name = "שבלי-אום אל-גנם"
                        },
                        new
                        {
                            Id = 180,
                            Name = "שלומי"
                        },
                        new
                        {
                            Id = 181,
                            Name = "שהם"
                        },
                        new
                        {
                            Id = 182,
                            Name = "תל מונד"
                        },
                        new
                        {
                            Id = 183,
                            Name = "תל שבע"
                        },
                        new
                        {
                            Id = 184,
                            Name = "טובא-זנגריה"
                        },
                        new
                        {
                            Id = 185,
                            Name = "טורעאן"
                        },
                        new
                        {
                            Id = 186,
                            Name = "יפיע"
                        },
                        new
                        {
                            Id = 187,
                            Name = "תל ציון"
                        },
                        new
                        {
                            Id = 188,
                            Name = "ירכא"
                        },
                        new
                        {
                            Id = 189,
                            Name = "יבנאל"
                        },
                        new
                        {
                            Id = 190,
                            Name = "ירוחם"
                        },
                        new
                        {
                            Id = 191,
                            Name = "יסוד המעלה"
                        },
                        new
                        {
                            Id = 192,
                            Name = "זרזיר"
                        },
                        new
                        {
                            Id = 193,
                            Name = "זמר"
                        },
                        new
                        {
                            Id = 194,
                            Name = "זכרון יעקב"
                        });
                });

            modelBuilder.Entity("SukotSystemCore.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone2")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("SukotSystemCore.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CityId")
                        .HasColumnType("integer");

                    b.Property<string>("Commits")
                        .HasColumnType("text");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<bool>("NeedsTool")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("PerformedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("PerformedRabbiId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RequestedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PerformedRabbiId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("SukotSystemCore.Models.Rabbi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("HomeCityId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone2")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("HomeCityId");

                    b.ToTable("Rabbis");
                });

            modelBuilder.Entity("CityRabbi", b =>
                {
                    b.HasOne("SukotSystemCore.Models.City", null)
                        .WithMany()
                        .HasForeignKey("CoveredCitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SukotSystemCore.Models.Rabbi", null)
                        .WithMany()
                        .HasForeignKey("RabbisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SukotSystemCore.Models.Order", b =>
                {
                    b.HasOne("SukotSystemCore.Models.City", "City")
                        .WithMany("Orders")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SukotSystemCore.Models.Customer", "RequestedCustomer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SukotSystemCore.Models.Rabbi", "PerformedRabbi")
                        .WithMany("HandledOrders")
                        .HasForeignKey("PerformedRabbiId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("City");

                    b.Navigation("PerformedRabbi");

                    b.Navigation("RequestedCustomer");
                });

            modelBuilder.Entity("SukotSystemCore.Models.Rabbi", b =>
                {
                    b.HasOne("SukotSystemCore.Models.City", "HomeCity")
                        .WithMany()
                        .HasForeignKey("HomeCityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HomeCity");
                });

            modelBuilder.Entity("SukotSystemCore.Models.City", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("SukotSystemCore.Models.Rabbi", b =>
                {
                    b.Navigation("HandledOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
